db.url=jdbc:h2:mem:gymcrm;DB_CLOSE_DELAY=-1
db.driver=org.h2.Driver
db.username=sa
db.password=

hibernate.dialect=org.hibernate.dialect.H2Dialect
hibernate.hbm2ddl.auto=create-drop
hibernate.show_sql=false
hibernate.format_sql=true
